### ISSUE TITLE
メンテナンスについて質問です

### ISSUE THREAD

**Issue by higoshi** [g0e/ccd3#22]
こちらのリポジトリは今後アップデートしていく予定はございますか？

**Comment by g0e** [comment]
う〜ん、ちょっと別件で使う可能性あるので手を入れようかと
思ってはいたのですが、かなり色々古くなっちゃっているのと、
修正するとして後方互換性とか他の方に使ってもらえる状態を
きちんと維持できるほどのコストはかけれないと思うので、
できれば他ライブラリへの載せ換えをオススメしたいですね。

**Comment by higoshi** [comment]
了解です、確かに大変そうですからね。ありがとうございました！
